// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                int64
	Email             string
	Username          string
	PasswordHash      string
	PasswordSalt      string
	FirstName         pgtype.Text
	LastName          pgtype.Text
	DisplayName       pgtype.Text
	Bio               pgtype.Text
	AvatarUrl         pgtype.Text
	PhoneNumber       pgtype.Text
	IsActive          pgtype.Bool
	IsVerified        pgtype.Bool
	Role              pgtype.Text
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	LastLoginAt       pgtype.Timestamptz
	EmailVerifiedAt   pgtype.Timestamptz
	PasswordChangedAt pgtype.Timestamptz
}
